apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: command
  name: command
spec:
  ports:
    - name: "59882"
      port: 59882
      targetPort: 59882
  selector:
    io.kompose.service: command
status:
  loadBalancer: {}
