apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kong-db
  name: kong-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kong-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-network: "true"
        io.kompose.service: kong-db
    spec:
      containers:
        - command:
            - /edgex-init/postgres_wait_install.sh
          env:
            - name: API_GATEWAY_HOST
              value: edgex-kong
            - name: API_GATEWAY_STATUS_PORT
              value: "8100"
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "true"
            - name: POSTGRES_DB
              value: kong
            - name: POSTGRES_PASSWORD_FILE
              value: /tmp/postgres-config/.pgpassword
            - name: POSTGRES_USER
              value: kong
            - name: PROXY_SETUP_HOST
              value: edgex-security-proxy-setup
            - name: SECRETSTORE_HOST
              value: edgex-vault
            - name: SECRETSTORE_PORT
              value: "8200"
            - name: SPIFFE_ENDPOINTSOCKET
              value: /tmp/edgex/secrets/spiffe/public/api.sock
            - name: SPIFFE_TRUSTBUNDLE_PATH
              value: /tmp/edgex/secrets/spiffe/trust/bundle
            - name: SPIFFE_TRUSTDOMAIN
              value: edgexfoundry.org
            - name: STAGEGATE_BOOTSTRAPPER_HOST
              value: edgex-security-bootstrapper
            - name: STAGEGATE_BOOTSTRAPPER_STARTPORT
              value: "54321"
            - name: STAGEGATE_DATABASE_HOST
              value: edgex-redis
            - name: STAGEGATE_DATABASE_PORT
              value: "6379"
            - name: STAGEGATE_DATABASE_READYPORT
              value: "6379"
            - name: STAGEGATE_KONGDB_HOST
              value: edgex-kong-db
            - name: STAGEGATE_KONGDB_PORT
              value: "5432"
            - name: STAGEGATE_KONGDB_READYPORT
              value: "54325"
            - name: STAGEGATE_READY_TORUNPORT
              value: "54329"
            - name: STAGEGATE_REGISTRY_HOST
              value: edgex-core-consul
            - name: STAGEGATE_REGISTRY_PORT
              value: "8500"
            - name: STAGEGATE_REGISTRY_READYPORT
              value: "54324"
            - name: STAGEGATE_SECRETSTORESETUP_HOST
              value: edgex-security-secretstore-setup
            - name: STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT
              value: "54322"
            - name: STAGEGATE_WAITFOR_TIMEOUT
              value: 60s
          image: postgres:13.8-alpine
          name: edgex-kong-db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /edgex-init
              name: edgex-init
              readOnly: true
            - mountPath: /tmp/postgres-config
              name: postgres-config
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /var/run
              name: kong-db-tmpfs0
            - mountPath: /tmp
              name: kong-db-tmpfs1
            - mountPath: /run
              name: kong-db-tmpfs2
      hostname: edgex-kong-db
      restartPolicy: Always
      volumes:
        - name: edgex-init
          persistentVolumeClaim:
            claimName: edgex-init
            readOnly: true
        - name: postgres-config
          persistentVolumeClaim:
            claimName: postgres-config
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - emptyDir:
            medium: Memory
          name: kong-db-tmpfs0
        - emptyDir:
            medium: Memory
          name: kong-db-tmpfs1
        - emptyDir:
            medium: Memory
          name: kong-db-tmpfs2
status: {}
