apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: secretstore-setup
  name: secretstore-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: secretstore-setup
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-network: "true"
        io.kompose.service: secretstore-setup
    spec:
      containers:
        - env:
            - name: ADD_KNOWN_SECRETS
              value: redisdb[app-rules-engine],redisdb[device-rest],message-bus[device-rest],redisdb[device-virtual],message-bus[device-virtual]
            - name: ADD_SECRETSTORE_TOKENS
            - name: API_GATEWAY_HOST
              value: edgex-kong
            - name: API_GATEWAY_STATUS_PORT
              value: "8100"
            - name: EDGEX_GROUP
              value: "2001"
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "true"
            - name: EDGEX_USER
              value: "2002"
            - name: PROXY_SETUP_HOST
              value: edgex-security-proxy-setup
            - name: SECRETSTORE_HOST
              value: edgex-vault
            - name: SECRETSTORE_PORT
              value: "8200"
            - name: SECUREMESSAGEBUS_TYPE
              value: redis
            - name: SPIFFE_ENDPOINTSOCKET
              value: /tmp/edgex/secrets/spiffe/public/api.sock
            - name: SPIFFE_TRUSTBUNDLE_PATH
              value: /tmp/edgex/secrets/spiffe/trust/bundle
            - name: SPIFFE_TRUSTDOMAIN
              value: edgexfoundry.org
            - name: STAGEGATE_BOOTSTRAPPER_HOST
              value: edgex-security-bootstrapper
            - name: STAGEGATE_BOOTSTRAPPER_STARTPORT
              value: "54321"
            - name: STAGEGATE_DATABASE_HOST
              value: edgex-redis
            - name: STAGEGATE_DATABASE_PORT
              value: "6379"
            - name: STAGEGATE_DATABASE_READYPORT
              value: "6379"
            - name: STAGEGATE_KONGDB_HOST
              value: edgex-kong-db
            - name: STAGEGATE_KONGDB_PORT
              value: "5432"
            - name: STAGEGATE_KONGDB_READYPORT
              value: "54325"
            - name: STAGEGATE_READY_TORUNPORT
              value: "54329"
            - name: STAGEGATE_REGISTRY_HOST
              value: edgex-core-consul
            - name: STAGEGATE_REGISTRY_PORT
              value: "8500"
            - name: STAGEGATE_REGISTRY_READYPORT
              value: "54324"
            - name: STAGEGATE_SECRETSTORESETUP_HOST
              value: edgex-security-secretstore-setup
            - name: STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT
              value: "54322"
            - name: STAGEGATE_WAITFOR_TIMEOUT
              value: 60s
          image: edgexfoundry/security-secretstore-setup:2.3.0
          name: edgex-security-secretstore-setup
          resources: {}
          volumeMounts:
            - mountPath: /edgex-init
              name: edgex-init
              readOnly: true
            - mountPath: /tmp/edgex/secrets
              name: secretstore-setup-claim1
            - mountPath: /tmp/kong
              name: kong
            - mountPath: /tmp/kuiper
              name: kuiper-sources
            - mountPath: /tmp/kuiper-connections
              name: kuiper-connections
            - mountPath: /vault/config
              name: vault-config
            - mountPath: /run
              name: secretstore-setup-tmpfs0
            - mountPath: /vault
              name: secretstore-setup-tmpfs1
      hostname: edgex-security-secretstore-setup
      restartPolicy: Always
      volumes:
        - name: edgex-init
          persistentVolumeClaim:
            claimName: edgex-init
            readOnly: true
        - name: secretstore-setup-claim1
          persistentVolumeClaim:
            claimName: secretstore-setup-claim1
        - name: kong
          persistentVolumeClaim:
            claimName: kong
        - name: kuiper-sources
          persistentVolumeClaim:
            claimName: kuiper-sources
        - name: kuiper-connections
          persistentVolumeClaim:
            claimName: kuiper-connections
        - name: vault-config
          persistentVolumeClaim:
            claimName: vault-config
        - emptyDir:
            medium: Memory
          name: secretstore-setup-tmpfs0
        - emptyDir:
            medium: Memory
          name: secretstore-setup-tmpfs1
status: {}
