apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-network: "true"
        io.kompose.service: ui
    spec:
      containers:
        - env:
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "true"
            - name: SERVICE_HOST
              value: edgex-ui-go
          image: edgexfoundry/edgex-ui:2.3.0
          name: edgex-ui-go
          ports:
            - containerPort: 4000
          resources: {}
      hostname: edgex-ui-go
      restartPolicy: Always
status: {}
